import type { Metadata } from "next";
import { GlobalContextProvider } from "./GlobalContextProvider";
import { LoginPopUp } from "./Global/Auth/Login/LoginPopUp";
import { RegisterPopUp } from "./Global/Auth/Register/RegisterPopUp";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <GlobalContextProvider>
          {children}
          <LoginPopUp />
          <RegisterPopUp />
        </GlobalContextProvider>
        <div id="portal" />
      </body>
    </html>
  );
}
